### ISSUE TITLE
Spork link broken in teaspoon documentation

### ISSUE THREAD

**Issue by stanweer1** [TeaspoonTDA/teaspoon#116]
Link broken end of https://teaspoontda.github.io/teaspoon/installation.html#spork

Change to https://teaspoontda.github.io/sporktda/index.html

**Comment by lizliz** [comment]
This needs additional thought. Now that @stanweer1 has added the fast zigzag stuff, which has the same lack of pip install problem that we had with every other zigzag solver, we're back to having zigzag included in the main folder. 

I'm also not super pumped about maintaining a parallel version of the code, not sure what to do with this long term.
