### ISSUE TITLE
FIgure out why the test_install only works up to Python 3.9 now.

### ISSUE THREAD

**Issue by lizliz** [TeaspoonTDA/teaspoon#118]
This shows up in the pull request for the test release #117 . I haven't gone back far enough to figure out what did this, but it shows install errors for everything past Python 3.9 (best guess is the tests don't run???). We should fix this before pulling it into the main brainch.

**Comment by barnesd8** [comment]
Okay this looks like it's fixed based on the history but please comment if incorrect

**Comment by lizliz** [comment]
Yep, I fixed it :D
