### ISSUE TITLE
[Joss Review] Bug(s?) discovered

### ISSUE THREAD

**Issue by yossibokorbleile** [TeaspoonTDA/teaspoon#137]
Hey! As part of the JOSS review, I have thus far found the following:
- When using ``MI_for_delay(data, plotting=False, method='basic', h_method='sturge', k=2, ranking=True)``, I get the error ``bins` must be positive, when an integer`` which appears to come from ``teaspoon/parameter_selection/MI_delay.py:496``
- there seems to be a path error with ``load_datasets.mnist()``, which I resolved locally

I will add more issues when I come across them. But I also can't continue the review until these have been resolved.

**Comment by maxchumley** [comment]
@yossibokorbleile could you give me more information about the data you are using so I can try to reproduce this error? When I use the example in our documentation the `MI_for_delay` function does not give me any errors.

**Comment by yossibokorbleile** [comment]
@maxchumley sorry for the delayed response, I will hunt down some more information and get back to you, but probably not before the start of December sorry (been teaching, and currently travelling).

**Comment by yossibokorbleile** [comment]
hi @maxchumley, sorry for taking so long to get back to you, I encountered the first issue when running :
```
from teaspoon.MakeData.DynSysLib.medical_data import EEG
from teaspoon.parameter_selection.MI_delay import MI_for_delay
data = EEG(SampleSize=5000, dynamic_state='normal')
MI_for_delay(data, plotting=False, method='basic', h_method='sturge', k=2, ranking=True)
```

**Comment by maxchumley** [comment]
@yossibokorbleile thank you for sending your code. I believe I figured out the issue. When you get data from any system in `DynSysLib` you need to store two variables `t` for time and `ts` for the signal so you would need `t, ts = EEG()`.  

However, there was also a small issue with the EEG function where the `ts` array would return a list with an array in it but I just submitted a PR to fix this problem. So on the current main branch to get your code to work you need to pass `data[1][0]` into mutual information to get the correct output or use `t, data = EEG()` and pass `data[0]` into mutual information. I hope this helps.
