### ISSUE TITLE
Bug in `read_data` from `fast_zigzag`

### ISSUE THREAD

**Issue by IanQS** [TeaspoonTDA/teaspoon#146]
Hey all! 

I'm using the [Fast Zigzag](https://teaspoontda.github.io/teaspoon/modules/TDA/fast_zigzag.html) module and unfortunately, I think there's a bug in the `read_data` function - 

```
def read_data(file_path):
    classes = {}
    with open(file_path, 'r') as file:
        for line in file:
            class_label, x, y = map(float, line.split())     # <------------------ offending line
            if class_label not in classes:
                classes[class_label] = {'x': [], 'y': []}
            classes[class_label]['x'].append(x)
            classes[class_label]['y'].append(y)

    for i in classes.keys():
        classes[i]['x'] = np.array(classes[i]['x'])
        classes[i]['y'] = np.array(classes[i]['y'])

    return classes
```

The first few rows of my file that was generated by `generate_input_file` looks like:

```
i 0
i 1
i 2
i 3
i 4
i 5
i 6
i 7
```
which means  that the code on the offending line tries to convert `i` into a float. Also, it looks like the code is making an assumption that there are two numbers of a given line, which isn't necessarily the case. See the following example taken directly from the [`fzz` github - filtration format](https://github.com/TDA-Jyamiti/fzz?tab=readme-ov-file#filtration-format)

```
i 0
i 1
i 2
i 0 1
i 0 2
i 1 2
i 0 1 2
d 0 1 2
d 1 2
d 0 1
```

**Comment by stanweer1** [comment]
Hi @IanQS, 

Is it possible for you to show your full code (assuming the following doesn't fix your problem)?

As far as I understand, it seems like you're trying to use read_data function to read an input file generated by generate_input_file; the function is only meant to be used to read in an output file from the C++ code for fzz. See their page for an example of an output file (basically three numbers per line). 

Please see the code on [Fast Zigzag](https://teaspoontda.github.io/teaspoon/modules/TDA/fast_zigzag.html) page to see how to use the functions. 

Let us know if this helps!

**Comment by IanQS** [comment]
Ahh, understood! I see now the issue. Thank you for taking the time to explain it to me!
