### ISSUE TITLE
CGSSN example not running

### ISSUE THREAD

**Issue by myersau3** [TeaspoonTDA/teaspoon#75]
I am getting the following error when trying to generate a CGSSN using the code in the documentation

#import needed packages
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
#teaspoon functions
from teaspoon.SP.network import cgss_graph
from teaspoon.SP.network_tools import remove_zeros
from teaspoon.SP.network_tools import make_network
from teaspoon.parameter_selection import MsPE

# Time series data
t = np.linspace(0,30,600)
ts = np.sin(t) + np.sin(2*t) #generate a simple time series

n = 3 #dimension of SSR
b = 8 #number of states per dimension
tau = MsPE.MsPE_tau(ts)

B_array = tsa_tools.cgss_binning(ts, n, tau, b) #binning array
SSR = tsa_tools.takens(ts, n, tau)  #state space reconstruction

A = cgss_graph(ts, B_array, n, tau) #adjacency matrix
A = remove_zeros(A) #remove nodes of unused permutation

G, pos = make_network(A) #get networkx representation

plt.figure(figsize = (8,8))
plt.title('Network', size = 20)
nx.draw(G, pos, with_labels=False, font_weight='bold', node_color='green',
        width=1, font_size = 10, node_size = 30)
plt.show()

![Screen Shot 2023-08-17 at 9 55 55 AM](https://github.com/TeaspoonTDA/teaspoon/assets/60787650/6309caa6-5ddf-40de-aeb3-2a7f77de7bf0)

This should be a simple fix just adding in the import of that module: from teaspoon.SP import tsa_tools

**Comment by maxchumley** [comment]
@myersau3 thank you for pointing this out. I just submitted a pull request to update this example in the documentation.

If you add the line "import teaspoon.SP.tsa_tools as tsa_tools" to the example it will give you the correct output.
